apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverse-proxy-svc
spec:
  # type: NodePort
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
    # nodePort: 30080
  selector:
    service: reverseproxy
