apiVersion: v1
kind: Service
metadata:
  # labels:
    # app: feed                                                   # <--- Used for applying a label to the service object.
  name: backend-feed                                              # <--- This is the service name, the one that you can curl and choose
  # namespace: default                                            # <--- If omitted, the default is used
  # selfLink: /api/v1/namespaces/default/services/feed #          # <--- Deprecated, no longer used
spec:
  ports:
  - port: 8080                                                    # <--- Port exposed by the Service inside the cluster (ClusterIP). Clients inside the cluster use this.
    protocol: TCP
    targetPort: 8080                                              # <--- Port exposed by the container in the Pod (the actual app listens here)
  selector:                                                       # <--- Must match the spec.template.metadata.labels in Deplyment.yaml
    app: feed                                                      
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
